apiVersion: v1
# always capitalise
kind: Secret
metadata:
  name: mongodb-secret
  #if we define username and password in form of key value pair add type as opaque
  # we can also pass credentials in form of tls certificate and type will change here
type: Opaque
data:
# encode in base64 and paste encoded string here
# in terminal - echo -n 'string_to_be_encoded' | base64
  mongo-root-username: cGF2YW4=
  mongo-root-password: cGF2YW5qb3NoaQ==
